# Spring looks for an application.yml file
guru:
  jms:
    username: JMS Username
    password: klfdskld1222
    dburl: some url


--- # File Seperator
spring:
  profiles: de

guru:
  jms:
    username: JMS Username $$$$$ German